export const environment = {
  production: true,
  baseApiUrl: 'https://api.mgoconnect.org',
  localApiUrl: 'https://localhost:44307',
  myPermitNowUrl: 'https://www.mypermitnow.org',
  mobileApiUrl: 'https://m.mygovernmentonline.org/api',
  customerPortalApiUrl: 'https://www.mygovernmentonline.org/api',
  siteUrl: 'https://demo.mgoconnect.org',
  myGovernmentOnlineOrg: 'https://www.mygovernmentonline.org',
  myGovernmentOnlineOrgDemo: 'https://demo.mygovernmentonline.org',
  redirectURL: 'https://demo.mgoconnect.org/auth/login',
  myProjectNowOrg: 'https://www.myprojectnow.org',
  geoMyGovernmentonlineOrg: `https://geo.mygovernmentonline.org`,
  assetsMgoconnectOrg: 'https://assets.mgoconnect.org',
};
